### ISSUE TITLE
Documentation: Emphasize that deviating from the defaults leads to pain, suffering, and hate

### ISSUE THREAD

**Issue by arubis** [hobby-kube/guide#22]
I am very pleased to have a running K8s cluster, and to report that doing so is very straightforward using the default values in https://github.com/hobby-kube/provisioning! 

My original plan was _not_ to follow all the defaults. After all, why pay for 4GB instances when 2GB instances are sufficient and half the price? Whether the underlying issues that I've run across are worth addressing is debatable, but having spent >10h trying to make what I'd figured were relatively minor modifications without success, I'd like to save others the same trouble.

In particular, the README here points to Scaleway's 2GB instances: "The very best offer at this time is definitely Scaleway where one gets a three node cluster up and running with enough memory (3x2GB) for less than €10/month." I'd inferred that using those 2GB instances with this project would be straightforward, and while I believe it it still _possible_, the tradeoff for the time investment in re-writing `module.swap` would be significant.

Among the things I tried with Scaleway before throwing up my hands and using all-default values (except for credentials):

 - Using Ubuntu Zesty instead of Xenial
>    Everything runs and `terraform apply` reports success, but kubectl reports that nodes never go ready due to DNS issues, and further investigation indicates that CNI isn't fully configured on the instances.
 - Using Scaleway ARM `C1` instances
>    This doesn't work because the `C1` instances are ARMv7l, which are 32-bit CPUs. Golang has known issues on 32-bit architectures, so `etcd` won't run without modification to the runtime environment.
  - Using Scaleway ARM `ARM64-2GB` instances
>    This doesn't work because (a) the install script for `etcd` is currently hardcoded for arch `amd64` (granted, not too hard to correct) and (b) despite initial appearances to the contrary, much like the `VC1S` type instances, `ARM64-2GB` Scaleway instances are limited to a combined 50GB of attached volumes at boot. (It was my belief that this latter was only true for `VC1S` that had me pressing on to get things working under ARM.)
  - Using Scaleway x86-64 `VC1S` instances
>    This doesn't work because you can't have more than 50GB of volumes attached to Scaleway 2GB volumes upon boot, and the provided boot images are already 50GB. This is already being tracked at #4 .

**Comment by pstadler** [comment]
In the beginning I was using VC1S instances on Scaleway w/o problems. The downside is that they don't allow you to attach more than 50GB storage, means you would have to provide something like a loop device or create a custom boot image (the latter is incredibly painful). How's the swap module related to this?

When it comes to ARM and different operating systems: It's quite hard to automate across different platforms because of k8s' dependencies and requirements when it comes to Kernel modules. Maybe you've better luck trying this with droplets on DigitalOcean.

Another problem is that Terraform is absolutely unreliable when it comes to module dependencies. If they would provide `depends_on` for modules ([see here](https://github.com/hashicorp/terraform/issues/10462)), the provisioning part of this guide could be improved a lot.

**Comment by arubis** [comment]
Ah, ignore my comments re: the swap module; I was working under the assumption that that was the use case for the additional block storage.

**Comment by mhussa** [comment]
I didn't quite understand this issue until I looked at the scaleway terraform config.  The current default terraform config for scaleway is to create VC1M (4gb mem, 2x50gb disk).

I didn't realise this either, assumed it would be VC1S.  c'est la vie.

**Comment by pstadler** [comment]
Just wanted to mention that the Terraform provider is now using VC1S instances as a default since the Rook storage provider (see the latest version of the guide) works with simple folders as well.

I'm closing this issue. Feel free to reopen.
