### ISSUE TITLE
What do you think about Rancher Longhorn distributed block storage solution?

### ISSUE THREAD

**Issue by harobed** [hobby-kube/guide#5]
Hi,

I didn't see [Rancher Longhorn](https://github.com/rancher/longhorn) in Distributed block storage solution list. Do you think that Longhorn can be an alternative to [portworx](https://portworx.com/)?

Best regards,
Stéphane

**Comment by pstadler** [comment]
Portworx works well enough for the time being, but it is proprietary software. Any potential alternative should match the following criteria besides being reliable:

- Dynamic volume provisioning using a `PersistentVolumeClaim`
- Deployment as a `DaemonSet` (no configuration/scripts outside of the manifest)
- Painless operations (preferably running within a single pod)
- Open source or a proprietary solution better than the current one

Longhorn could indeed be an alternative if they integrate better with Kubernetes.

**Comment by pstadler** [comment]
I'm currently evaluating [Rook](https://rook.io), means it's running on my cluster for a couple of weeks. So far so good! Discussions going on here: https://github.com/hobby-kube/manifests/pull/1

As soon as I find the time, I'm most likely going to update the guide to recommend using Rook. Mostly because it's an open source solution, offers straight forward setup and seems pretty robust.
